name: acorn
channels:
  - gurobi
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - cython=0.29.24
  - gurobi=9.1.2=py37_0
  - matplotlib=3.3.4
  - numpy=1.20.3
  - pillow=8.3.1
  - pip=21.1.3
  - python=3.7.10
  - pytorch=1.8.1
  - scikit-image=0.18.1
  - scipy=1.6.2
  - tensorboard=2.5.0=py_0
  - torchvision=0.9.1=py37_cu102
  - tqdm=4.61.2=pyhd3eb1b0_1
  - pip:
    - configargparse==1.5.1
    - mrcfile==1.3.0
    - opencv-python==4.5.3.56
    - pycollada==0.7.1
    - pymcubes==0.1.2
    - trimesh==3.9.25
